name: Zenchantments
main: zedly.zenchantments.Zenchantments
version: ${project.version}
commands:
  arrow:
    description: Gives basic access; /arrow help.
    usage: /arrow
    default: true
  ench:
    description: Gives basic access; /ench help.
    usage: /ench
    default: true
permissions:
  zenchantments.arrow.get:
    description: Allows for crafting elemental arrows
    default: true
  zenchantments.arrow.use:
    description: Allows for use of elemental arrows
    default: true
  zenchantments.enchant.get:
    description: Allows for obtaining custom enchantments
    default: true
  zenchantments.enchant.use:
    description: Allows for use of custom enchantments
    default: true
  zenchantments.command.arrow:
    description: Sets the arrow in hand to the desired elemental arrow
    default: false
  zenchantments.command.enchant:
    description: Enchants the item in hand
    default: false
  zenchantments.command.give:
    description: Allows for giving new, enchanted items to selected players
    default: false
  zenchantments.command.info:
    description: Returns descriptions of the enchantments or arrows in hand
    default: true
  zenchantments.command.list:
    description: Returns a list of enchantments and arrows
    default: true
  zenchantments.command.onoff:
    description: Enables or disables certain custom enchantments for the user
    default: true
  zenchantment.command.reload:
    description: Reloads the plugin config file
    default: false
  zenchantments.*:
    children:
      zenchantments.arrow.get: true
      zenchantments.arrow.use: true
      zenchantments.enchant.get: true
      zenchantments.enchant.use: true
      zenchantments.command.arrow: true
      zenchantments.command.enchant: true
      zenchantments.command.give: true
      zenchantments.command.info: true
      zenchantments.command.list: true
      zenchantments.command.onoff: true
      zenchantments.command.reload: true