name: Zenchantments
main: zedly.zenchantments.Zenchantments
version: 1.2.0
commands:
  arrow:
    description: Gives basic access; /arrow help.
    usage: /arrow
    default: true
  ench:
    description: Gives basic access; /ench help.
    usage: /ench
    default: true
permissions:
  zenchantments.command.arrow:
    description: Sets the arrow the user is holding to the desired Elemental Arrow
    default: false
  zenchantments.item.arrows:
    description: Allows for use of Elemental Arrows
    default: false
  zenchantments.command.enchant:
    description: Enchants the item the user is holding
    default: false
  zenchantments.enchant.get:
    description: Allows for obtaining custom enchantments
    default: true
  zenchantments.command.give:
    description: Allows for giving new, enchanted items to selected players
    default: true
  zenchantments.command.info:
    description: Returns descriptions of the enchantments or arrow in hand
    default: false
  zenchantments.command.list:
    description: Returns a list of enchantments and arrows
    default: false
  zenchantments.command.onoff:
    description: Enables or disables certain custom enchantments for the user
    default: false
  zenchantments.enchant.use:
    description: Allows for use of custom enchantments
    default: true
  zenchantments.arrow.craft:
    description: Allows for use of custom enchantments
    default: false
  zenchantment.command.reload:
    description: Reloads the plugin config file
    default: false
  zenchantments.*:
    children:
      zenchantments.command.arrow: true
      zenchantments.item.arrows: true
      zenchantments.command.enchant: true
      zenchantments.enchant.get: true
      zenchantments.command.give: true
      zenchantments.command.info: true
      zenchantments.command.list: true
      zenchantments.command.onoff: true
      zenchantments.enchant.use: true
      zenchantments.arrow.craft: true
      zenchantments.command.reload: true